### ISSUE TITLE
Error after download - ServiceManager::get was unable to fetch or create an instance for ApplicationConfig

### ISSUE THREAD

**Issue by stratease** [GotCms/GotCms#274]
```
Notice: Undefined variable: configuration in /var/www/got-cms.dev/public/index.php on line 33

Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for ApplicationConfig' in /var/www/got-cms.dev/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:529 Stack trace: #0 /var/www/got-cms.dev/vendor/zendframework/zendframework/library/Zend/Mvc/Service/ModuleManagerFactory.php(41): Zend\ServiceManager\ServiceManager->get('ApplicationConf...') #1 [internal function]: Zend\Mvc\Service\ModuleManagerFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'modulemanager', 'ModuleManager') #2 /var/www/got-cms.dev/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(902): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'modulemanager', 'ModuleManager') #3 /var/www/got-cms.dev/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php(1032): Zend\ServiceManager\ServiceManager->createServiceV in /var/www/got-cms.dev/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 529
```

This was after running the create project command, and then attempting to browse to the /install/ path through my browser. I'm using apache 2, with the configuration list on this installation guide. And I confirmed the user permissions on the folders listed.

Apache:
```
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        ServerName www.got-cms.dev
        <Directory /var/www/got-cms.dev/public>
Options Indexes FollowSymLinks MultiViews
        Order allow,deny
        Allow from all
        AllowOverride All
RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ index.php [NC,L]
        </Directory>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/got-cms.dev/public

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>
```
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**Comment by automatix** [comment]
Having the same error now. I have definitely not deleted the Zend module. It simply doesn't get loaded or gets saved wrongly by the composer. I first installed the CMS with the composer:

    $ composer create-project gotcms/gotcms /path/to/application 1.5.1

Following folder structure was created:

    /...
    /vendor
    /vendor/autoload.php
    /vendor/composer
    /vendor/gotcms
    /vendor/...
    /vendor/symfony
    /vendor/vendor
    /vendor/vendor/Assetic
    /vendor/vendor/AssetManager
    /vendor/vendor/elFinder
    /vendor/vendor/Parsedown
    /vendor/vendor/SVGGraph
    /vendor/vendor/Zend
    /vendor/zendframework
    /...

So the was a `Zend` foolder created, but it was placed into a wrong folder `/vendor/vendor`.

Then I tried to delete the whole `/vendor` folder and execute `composer install`. Teh composer created then a new `/vendor` folder, but without a `Zend` and also without an additional `vendor` folder in it.

I moved the `Zend` folder from `/vendor/vendor` to `/vendor` manually. Now it works. But it's still ust a workaround.

**Comment by PierreRambaud** [comment]
I don't know how to reproduce this bug, I do the sames commands and this is what I got:
```bash
$ composer create-project gotcms/gotcms gotcms 1.5.1
Installing gotcms/gotcms (1.5.1)
  - Installing gotcms/gotcms (1.5.1)
    Loading from cache

Created project in gotcms
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing psr/log (1.0.0)
    Downloading: 100%         

  - Installing symfony/event-dispatcher (v2.6.3)
    Downloading: 100%         

  - Installing guzzle/guzzle (v3.9.2)
    Downloading: 100%         

  - Installing symfony/stopwatch (v2.6.3)
    Downloading: 100%         

  - Installing symfony/filesystem (v2.6.3)
    Downloading: 100%         

  - Installing symfony/config (v2.6.3)
    Downloading: 100%         

  - Installing symfony/console (v2.6.3)
    Downloading: 100%         

  - Installing symfony/yaml (v2.6.3)
    Downloading: 100%         

  - Installing satooshi/php-coveralls (dev-master 2fbf803)
    Cloning 2fbf803803d179ab1082807308a67bbd5a760c70

  - Installing squizlabs/php_codesniffer (1.4.8)
    Downloading: 100%         

  - Installing gotcms/gotsniffs (dev-master f15ad50)
    Cloning f15ad506d6c99588d5ebb3e1b527ebaa5733ff86

  - Installing packagist/yuicompressor-bin (dev-master 7d99543)
    Cloning 7d99543131ed6aaa70d2183f09fdef3a1ca1fe08

  - Installing mockery/mockery (0.9.0)
    Downloading: 100%         

  - Installing zendframework/zendxml (1.0.0)
    Downloading: 100%         

  - Installing symfony/process (v2.6.3)
    Downloading: 100%         

  - Installing kriswallsmith/assetic (v1.1.3)
    Downloading: 100%         

  - Installing zendframework/zendframework (2.3.3)
    Downloading: 100%         

  - Installing rwoverdijk/assetmanager (1.4.1)
    Downloading: 100%         

  - Installing phpunit/php-text-template (1.2.0)
    Downloading: 100%         

  - Installing phpunit/phpunit-mock-objects (1.2.3)
    Downloading: 100%         

  - Installing phpunit/php-timer (1.0.5)
    Downloading: 100%         

  - Installing phpunit/php-token-stream (1.2.2)
    Downloading: 100%         

  - Installing phpunit/php-file-iterator (1.3.4)
    Downloading: 100%         

  - Installing phpunit/php-code-coverage (1.2.18)
    Downloading: 100%         

  - Installing phpunit/phpunit (3.7.38)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
satooshi/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
kriswallsmith/assetic suggests installing twig/twig (Assetic provides the integration with the Twig templating engine)
kriswallsmith/assetic suggests installing leafo/lessphp (Assetic provides the integration with the lessphp LESS compiler)
kriswallsmith/assetic suggests installing leafo/scssphp (Assetic provides the integration with the scssphp SCSS compiler)
kriswallsmith/assetic suggests installing ptachoire/cssembed (Assetic provides the integration with phpcssembed to embed data uris)
kriswallsmith/assetic suggests installing leafo/scssphp-compass (Assetic provides the integration with the SCSS compass plugin)
zendframework/zendframework suggests installing ext-intl (ext/intl for i18n features (included in default builds of PHP))
zendframework/zendframework suggests installing doctrine/annotations (Doctrine Annotations >=1.0 for annotation features)
zendframework/zendframework suggests installing ircmaxell/random-lib (Fallback random byte generator for Zend\Math\Rand if OpenSSL/Mcrypt extensions are unavailable)
zendframework/zendframework suggests installing ocramius/proxy-manager (ProxyManager 0.5.* to handle lazy initialization of services)
zendframework/zendframework suggests installing zendframework/zendpdf (ZendPdf for creating PDF representations of barcodes)
zendframework/zendframework suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha for rendering ReCaptchas in Zend\Captcha and/or Zend\Form)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
prambaud@lin0001:~/projects/php$ ll gotcms/vendor/
total 88K
drwxr-xr-x 21 prambaud prambaud 4.0K Jan 15 10:11 .
drwxr-xr-x 13 prambaud prambaud 4.0K Jan 15 10:11 ..
drwxr-xr-x  9 prambaud prambaud 4.0K Oct 31 17:10 Assetic
drwxr-xr-x  5 prambaud prambaud 4.0K Oct 31 17:10 AssetManager
-rw-r--r--  1 prambaud prambaud  183 Jan 15 10:11 autoload.php
drwxr-xr-x  2 prambaud prambaud 4.0K Jan 15 10:11 composer
drwxr-xr-x  2 prambaud prambaud 4.0K Oct 31 17:10 elFinder
-rw-r--r--  1 prambaud prambaud    0 Oct 31 17:10 .gitignore
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 gotcms
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 guzzle
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 kriswallsmith
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 mockery
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 packagist
drwxr-xr-x  3 prambaud prambaud 4.0K Oct 31 17:10 Parsedown
drwxr-xr-x  9 prambaud prambaud 4.0K Jan 15 10:11 phpunit
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 psr
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 rwoverdijk
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 satooshi
drwxr-xr-x  3 prambaud prambaud 4.0K Jan 15 10:11 squizlabs
drwxr-xr-x  2 prambaud prambaud 4.0K Oct 31 17:10 SVGGraph
drwxr-xr-x  9 prambaud prambaud 4.0K Jan 15 10:11 symfony
drwxr-xr-x 51 prambaud prambaud 4.0K Oct 31 17:10 Zend
drwxr-xr-x  4 prambaud prambaud 4.0K Jan 15 10:11 zendframework
prambaud@lin0001:~/projects/php$
```

More if the project is installed via composer, a `vendor/zendframework` directory must be created and a `vendor/autoload.php` file too.

My composer version
```bash
$ composer --version
Composer version 1.0-dev (8db7420f025b5c4705ce6f66b65c6d2b52d27813) 2015-01-12 23:02:29
```

Regards
